#manifests file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
      annotations:
        eks.amazonaws.com/compute-type: fargate
    spec:
      containers:
      - name: my-web-app
        image: purna88836/my-docker-image:latest
        ports:
        - containerPort: 80

apiVersion: eks.amazonaws.com/v1alpha1
kind: FargateProfile
metadata:
  name: my-fargate-profile
  namespace: default  # Specify the namespace wher you want to deploy pods on Fargate
selectors:
  - namespace: default
    labels:
      app: my-web-app